#!/usr/bin/env python3
"""Cluster A/B/C atoms into a milestone-ordered candidate backlog.

Output: coverage/dev-plan-candidate.md

⚠️  This is a SCAFFOLD, not a verified plan.
    Milestone assignments are auto-generated by keyword mapping.
    To become a "no-omission" plan:
      1. Human review of each atom's milestone assignment
      2. Fill features.toml with real attribution (A/B/C anchors per feature)
      3. Implement gates 3 (mutation injection) and 4 (negative test diff)
      4. Write a Rust compiler that passes the tests
"""

from __future__ import annotations
import sys
from pathlib import Path
from collections import defaultdict

sys.path.insert(0, str(Path(__file__).parent))
from models import load_toml, COVERAGE_DIR

# ── Spec atom → milestone (by atom_id suffix after "spec:") ──────────────
SPEC_MS: dict[str, str] = {
    # M0: Lexer / Scanner
    "Source_code_representation": "M0", "Characters": "M0", "Letters_and_digits": "M0",
    "Lexical_elements": "M0", "Comments": "M0", "Tokens": "M0", "Semicolons": "M0",
    "Identifiers": "M0", "Keywords": "M0", "Operators_and_punctuation": "M0",
    "Integer_literals": "M0", "Floating-point_literals": "M0",
    "Imaginary_literals": "M0", "Rune_literals": "M0", "String_literals": "M0",
    # M1: Types & Constants
    "Constants": "M1", "Variables": "M1", "Types": "M1",
    "Boolean_types": "M1", "Numeric_types": "M1", "String_types": "M1",
    "Array_types": "M1", "Slice_types": "M1", "Struct_types": "M1",
    "Pointer_types": "M1", "Function_types": "M1", "Interface_types": "M1",
    "Map_types": "M1", "Channel_types": "M1",
    "Properties_of_types_and_values": "M1", "Representation_of_values": "M1",
    "Underlying_types": "M1", "Type_identity": "M1", "Assignability": "M1",
    "Representability": "M1", "Method_sets": "M1", "Type_unification_rules": "M1",
    # M2: Declarations & Scope
    "Blocks": "M2", "Declarations_and_scope": "M2", "Label_scopes": "M2",
    "Blank_identifier": "M2", "Predeclared_identifiers": "M2",
    "Exported_identifiers": "M2", "Uniqueness_of_identifiers": "M2",
    "Constant_declarations": "M2", "Iota": "M2", "Type_declarations": "M2",
    "Type_parameter_declarations": "M2", "Variable_declarations": "M2",
    "Short_variable_declarations": "M2", "Function_declarations": "M2",
    "Method_declarations": "M2",
    # M3: Expressions
    "Expressions": "M3", "Operands": "M3", "Qualified_identifiers": "M3",
    "Composite_literals": "M3", "Function_literals": "M3",
    "Primary_expressions": "M3", "Selectors": "M3", "Method_expressions": "M3",
    "Method_values": "M3", "Index_expressions": "M3", "Slice_expressions": "M3",
    "Type_assertions": "M3", "Calls": "M3", "Instantiations": "M3",
    "Type_inference": "M3", "Operators": "M3", "Arithmetic_operators": "M3",
    "Comparison_operators": "M3", "Logical_operators": "M3",
    "Address_operators": "M3", "Receive_operator": "M3", "Conversions": "M3",
    "Constant_expressions": "M3", "Order_of_evaluation": "M3",
    # M4: Statements
    "Statements": "M4", "Terminating_statements": "M4", "Empty_statements": "M4",
    "Labeled_statements": "M4", "Expression_statements": "M4",
    "Send_statements": "M4", "IncDec_statements": "M4",
    "Assignment_statements": "M4", "If_statements": "M4",
    "Switch_statements": "M4", "For_statements": "M4", "Go_statements": "M4",
    "Select_statements": "M4", "Return_statements": "M4",
    "Break_statements": "M4", "Continue_statements": "M4",
    "Goto_statements": "M4", "Fallthrough_statements": "M4",
    "Defer_statements": "M4",
    # M5: Built-ins & Packages
    "Built-in_functions": "M5", "Appending_and_copying_slices": "M5",
    "Clear": "M5", "Close": "M5", "Complex_numbers": "M5",
    "Deletion_of_map_elements": "M5", "Length_and_capacity": "M5",
    "Making_slices_maps_and_channels": "M5", "Min_and_max": "M5",
    "Allocation": "M5", "Handling_panics": "M5", "Bootstrapping": "M5",
    "Packages": "M5", "Source_file_organization": "M5",
    "Package_clause": "M5", "Import_declarations": "M5",
    "An_example_package": "M5",
    # M6: Runtime & Init
    "Program_initialization_and_execution": "M6", "The_zero_value": "M6",
    "Package_initialization": "M6", "Program_initialization": "M6",
    "Program_execution": "M6", "Errors": "M6", "Run_time_panics": "M6",
    "System_considerations": "M6", "Size_and_alignment_guarantees": "M6",
    # Non-claimable (narrative / meta)
    "Introduction": "N/A", "Notation": "N/A", "Appendix": "N/A",
    "Language_versions": "N/A",
}


def impl_ms(rec: dict) -> str:
    kind = rec.get("kind", "")
    name = rec.get("name", "")
    if kind == "pragma":
        base = name.replace("//go:", "")
        if base == "build":
            return "M2"
        if base == "embed":
            return "M5"
        if base in ("linkname", "linknamestd"):
            return "M5"
        if base in ("noescape", "uintptrescapes", "uintptr", "uintptrkeepalive"):
            return "M7"
        if base == "noinline":
            return "M7"
        if base == "nointerface":
            return "M2"
        if base.startswith("cgo"):
            return "M5"
        if base in ("wasmimport", "wasmexport"):
            return "M7.2-T3"
        if base == "generate":
            return "M0"
        return "M5"
    if kind == "flag":
        if name == "Lang":
            return "M0"
        return "M7"  # all other flags = compiler driver / infra
    if kind == "rules":
        if name in ("generic.rules", "dec.rules", "dec64.rules",
                     "divisible.rules", "divmod.rules"):
            return "M7"
        if name.startswith("AMD64") or name == "simdAMD64.rules":
            return "M7.2-T1"
        if name.startswith("ARM64") or name == "simdARM64.rules":
            return "M7.2-T2"
        return "M7.2-T3"
    if kind == "obj":
        arch = rec.get("arch", "")
        if arch == "x86":
            return "M7.2-T1"
        if arch == "arm64":
            return "M7.2-T2"
        return "M7.2-T3"
    return "M?"


def test_ms(rec: dict) -> str:
    tid = rec.get("test_id", "")
    parts = tid.split(":")
    layer = parts[0] if parts else ""

    # L5: script tests — only 2 parts ("L5:filename.txt"), no directory.
    # Must check before the len < 3 guard.
    if layer == "L5":
        return "M5"

    if len(parts) < 3:
        return "M?"

    d = parts[1]

    # Root dir (test/*.go) — mixed across all front-end milestones.
    if d in ("", "."):
        return "M0-M5"
    # Backend / codegen
    if d == "codegen":
        return "M7"
    if d == "escape":
        return "M7"
    if d == "abi":
        return "M7"
    if d == "dwarf":
        return "M7"
    if d == "simd":
        return "M7.2-T1"
    # Generics
    if d.startswith("typeparam"):
        return "M2"
    # Front-end by topic
    if d == "syntax":
        return "M0"
    if d == "typeswitch":
        return "M3"
    if d in ("iface", "interface"):
        return "M2"
    if d == "typecheck":
        return "M2"
    if d == "chan":
        return "M4"
    if d == "ken":
        return "M0-M5"  # Ken Thompson's suite — mixed
    if d == "arenas":
        return "M5"
    # Runtime/internal
    if d.startswith("internal"):
        return "M6"
    # Regression — actually needs per-file triage
    if d == "fixedbugs":
        return "M6"
    return f"M? ({d})"


# ── Ordering & titles ────────────────────────────────────────────────────
MILESTONE_ORDER = [
    "M0", "M1", "M2", "M3", "M4", "M5", "M6", "M7",
    "M7.2-T1", "M7.2-T2", "M7.2-T3",
    "N/A", "M0-M5", "M?",
]

MS_TITLE: dict[str, str] = {
    "M0": "M0: 词法分析 (Lexer / Scanner)",
    "M1": "M1: 类型与常量 (Types & Constants)",
    "M2": "M2: 声明与作用域 (Declarations & Scope)",
    "M3": "M3: 表达式 (Expressions)",
    "M4": "M4: 语句 (Statements)",
    "M5": "M5: 内建函数与包 (Built-ins & Packages)",
    "M6": "M6: 运行时与初始化 (Runtime & Init)",
    "M7": "M7: 中端与驱动 (SSA, Inline, Escape, Driver)",
    "M7.2-T1": "M7.2-T1: amd64 后端 (必做)",
    "M7.2-T2": "M7.2-T2: arm64 后端 (应做)",
    "M7.2-T3": "M7.2-T3: 其余 9 架构 (scope-excluded)",
    "N/A": "N/A: 叙述性章节 (非编译器行为, claimable=false 候选)",
    "M0-M5": "M0-M5: 混合 (test/ 根目录, 需逐文件 triage)",
    "M?": "M?: 未分类 (需 triage)",
}


def main() -> int:
    cov = COVERAGE_DIR
    specs = load_toml(cov / "spec_atoms.toml").get("spec_atoms", [])
    impls = load_toml(cov / "impl_atoms.toml").get("impl_atoms", [])
    tests = load_toml(cov / "official-tests.toml").get("test_atoms", [])
    feats = load_toml(cov / "features.toml").get("features", [])

    # Compute claimed atom IDs from features.toml
    claimed: set[str] = set()
    for f in feats:
        claimed.update(f.get("spec_atoms", []))
        claimed.update(f.get("impl_atoms", []))
        claimed.update(f.get("test_ids", []))
        claimed.update(f.get("negative_test_ids", []))

    # Assign milestones
    spec_ms = {r["atom_id"]: SPEC_MS.get(r["atom_id"].replace("spec:", ""), "M?") for r in specs}
    impl_ms_map = {r["atom_id"]: impl_ms(r) for r in impls}
    test_ms_map = {r["test_id"]: test_ms(r) for r in tests}

    # Group by milestone
    ms: dict[str, dict] = defaultdict(lambda: {
        "specs": [], "impls": [], "tests": [],
        "spec_c": 0, "spec_u": 0,
        "impl_c": 0, "impl_u": 0,
        "test_c": 0, "test_u": 0,
    })

    for r in specs:
        m = spec_ms[r["atom_id"]]
        ms[m]["specs"].append(r)
        if r["atom_id"] in claimed:
            ms[m]["spec_c"] += 1
        else:
            ms[m]["spec_u"] += 1

    for r in impls:
        m = impl_ms_map[r["atom_id"]]
        ms[m]["impls"].append(r)
        if r["atom_id"] in claimed:
            ms[m]["impl_c"] += 1
        else:
            ms[m]["impl_u"] += 1

    for r in tests:
        m = test_ms_map[r["test_id"]]
        ms[m]["tests"].append(r)
        if r["test_id"] in claimed:
            ms[m]["test_c"] += 1
        else:
            ms[m]["test_u"] += 1

    # ── Generate markdown ──────────────────────────────────────────────
    L: list[str] = []
    L.append("# 候选开发计划（auto-clustered from A/B/C）")
    L.append("")
    L.append("> ⚠️ **这是候选骨架，不是已验证的计划。**")
    L.append("> 每个 atom 的里程碑归属是按关键词自动分配的，未经人工审核。")
    L.append("> 要变成「零遗漏」计划，需要：")
    L.append("> 1. 人工审核每个 atom 的里程碑归属")
    L.append("> 2. 填充 `features.toml`（每条 feature 给出 A/B/C 三侧锚点 + 里程碑 + target_dim）")
    L.append("> 3. 实现闸三（变异注入差分）和闸四（负测试差分）")
    L.append("> 4. 写一个能通过测试的 Rust 编译器")
    L.append("")
    L.append(f"> 基线：go1.27.1  |  A(spec)={len(specs)}  B(impl)={len(impls)}  C(test)={len(tests)}  "
             f"features={len(feats)}  claimed={len(claimed)}")
    L.append("")

    # ── Summary table ──────────────────────────────────────────────────
    L.append("## 里程碑总览")
    L.append("")
    L.append("| 里程碑 | 主题 | spec | impl | test | 已认领 | 未认领 |")
    L.append("|---|---|---:|---:|---:|---:|---:|")
    for m in MILESTONE_ORDER:
        if m not in ms:
            continue
        d = ms[m]
        total = len(d["specs"]) + len(d["impls"]) + len(d["tests"])
        if total == 0:
            continue
        claimed_n = d["spec_c"] + d["impl_c"] + d["test_c"]
        unclaimed = total - claimed_n
        title = MS_TITLE.get(m, m)
        L.append(f"| {m} | {title.split(': ', 1)[-1]} "
                 f"| {len(d['specs'])} | {len(d['impls'])} | {len(d['tests'])} "
                 f"| {claimed_n} | {unclaimed} |")
    L.append("")

    # ── Per-milestone detail ──────────────────────────────────────────
    L.append("## 逐里程碑明细")
    L.append("")
    for m in MILESTONE_ORDER:
        if m not in ms:
            continue
        d = ms[m]
        total = len(d["specs"]) + len(d["impls"]) + len(d["tests"])
        if total == 0:
            continue
        title = MS_TITLE.get(m, m)
        L.append(f"### {title}")
        L.append("")

        # Spec atoms
        if d["specs"]:
            L.append(f"**spec 条款 ({len(d['specs'])})**")
            L.append("")
            for r in d["specs"]:
                aid = r["atom_id"]
                mark = "✓" if aid in claimed else "○"
                L.append(f"- {mark} `{aid}` — {r.get('title', '')}")
            L.append("")

        # Impl atoms
        if d["impls"]:
            L.append(f"**impl 原子 ({len(d['impls'])})**")
            L.append("")
            # Group by kind
            by_kind: dict[str, list] = defaultdict(list)
            for r in d["impls"]:
                by_kind[r.get("kind", "?")].append(r)
            for kind in ("pragma", "flag", "rules", "obj"):
                if kind not in by_kind:
                    continue
                recs = by_kind[kind]
                L.append(f"- {kind} ({len(recs)}):")
                for r in recs:
                    aid = r["atom_id"]
                    mark = "✓" if aid in claimed else "○"
                    extra = ""
                    if "pass" in r:
                        extra = f" [pass={r['pass']}, rules={r.get('rule_count', '?')}]"
                    elif "arch" in r:
                        extra = f" [arch={r['arch']}, loc={r.get('loc', '?')}]"
                    elif "help" in r:
                        extra = f" — {r['help'][:60]}"
                    L.append(f"  - {mark} `{aid}`{extra}")
            L.append("")

        # Test atoms
        if d["tests"]:
            L.append(f"**测试 ({len(d['tests'])})**")
            L.append("")
            # Group by sub-directory
            by_dir: dict[str, list] = defaultdict(list)
            for r in d["tests"]:
                parts = r["test_id"].split(":")
                subdir = parts[1] if len(parts) > 1 else "?"
                by_dir[subdir].append(r)
            for subdir in sorted(by_dir.keys()):
                recs = by_dir[subdir]
                claimed_n = sum(1 for r in recs if r["test_id"] in claimed)
                label = subdir if subdir else "(root)"
                L.append(f"- `L?:{label}` — {len(recs)} 个（已认领 {claimed_n}）")
            L.append("")

        # Candidate feature_ids (empty — to be filled)
        unclaimed = (d["spec_u"] + d["impl_u"] + d["test_u"])
        if unclaimed > 0:
            L.append(f"*候选 feature_ids：{unclaimed} 个未认领 atom 待归属（人工填写 `features.toml`）*")
            L.append("")

    # ── Current attribution ──────────────────────────────────────────
    L.append("## 当前认领状态（features.toml）")
    L.append("")
    if not feats:
        L.append("*(空)*")
    else:
        L.append("| feature_id | 里程碑 | target | status | spec | impl | test | neg | mut |")
        L.append("|---|---|---|---|---:|---:|---:|---:|:---:|")
        for f in feats:
            has_mut = "✓" if f.get("mutation_case_id") else "✗"
            L.append(f"| `{f['feature_id']}` | {f.get('main_task', '?')} "
                     f"| {f.get('target_dim', '?')} | {f.get('status', '?')} "
                     f"| {len(f.get('spec_atoms', []))} | {len(f.get('impl_atoms', []))} "
                     f"| {len(f.get('test_ids', []))} | {len(f.get('negative_test_ids', []))} "
                     f"| {has_mut} |")
    L.append("")

    # ── Gap analysis ──────────────────────────────────────────────────
    total_atoms = len(specs) + len(impls) + len(tests)
    total_unclaimed = total_atoms - len(claimed)
    L.append("## 缺口分析（到「已验证计划」还差什么）")
    L.append("")
    L.append(f"| 项 | 状态 |")
    L.append(f"|---|---|")
    L.append(f"| 闸一：机械生成三集 | ✅ 已实现（A={len(specs)}, B={len(impls)}, C={len(tests)}）|")
    L.append(f"| 闸二：三角 diff | ✅ 已实现（`triangle_diff.py`，{total_unclaimed} 个未认领）|")
    L.append(f"| 闸三：变异注入差分 | ❌ 未实现（需写 harness：故意改 reference 一个行为，验证 harness 能抓到）|")
    L.append(f"| 闸四：负测试差分 | ❌ 未实现（需写 harness：reference 拒绝的代码 Rust 也必须拒绝）|")
    L.append(f"| features.toml 归属 | ⏳ {len(feats)} 条（需人工填写到覆盖全部 atom）|")
    L.append(f"| Rust 编译器 | ❌ 不存在（`nobody0726/go-compiler-rust` 有 13 个 crate 骨架）|")
    L.append("")
    L.append("**下一步建议**：")
    L.append(f"1. 从 M0（词法）开始逐条人工审核本骨架的 spec 归属，填写 `features.toml`")
    L.append(f"2. 对 M0 的每条 spec clause，找到对应的 B 集 impl atom（pragma/flag/包）和 C 集测试")
    L.append(f"3. 用 `validate_features.py` 校验每条 feature 四道闸（静态半边）")
    L.append(f"4. 扩 B 集加导出符号（当前只有 pragma/flag/rules/obj，缺 `defer`/`range` 改写等纯源码实现）")
    L.append("")

    md = "\n".join(L)
    out = cov / "dev-plan-candidate.md"
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out} ({len(md)} bytes, {len(L)} lines)")
    print(f"milestones with atoms: {len([m for m in MILESTONE_ORDER if m in ms and sum(len(ms[m][k]) for k in ('specs','impls','tests')) > 0])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
